### ISSUE TITLE
Inquiry for Processed Dataset

### ISSUE THREAD

**Issue by Petrichor625** [schmidt-ju/crat-pred#10]
Your paper has provided us with great insights and inspiration for our own research!
I attempted to preprocess the dataset using the "python3 preprocess.py" command. However, I have been facing some difficulties and have not been able to successfully preprocess the dataset. I have also configured the relevant environment, but to no avail.
Therefore, I would like to kindly request your assistance in obtaining the processed dataset from your paper. If possible, I would be grateful if you could share it , thank you very much!!

**Comment by schmidt-ju** [comment]
This was related to an issue in the dataset path.
