### ISSUE TITLE
Question for the result visualization

### ISSUE THREAD

**Issue by Petrichor625** [schmidt-ju/crat-pred#12]
Thank you so much for sharing the code.
I would like to use the result visualization in Crat-pred code, but has the visualization code shown on the github page not been shared? Can you share it ?
Thank U!

**Comment by schmidt-ju** [comment]
Hey :)

there have been prior requests regarding the visualization.
Please check them out:
#9 #6 

@Cram3r95 did an amazing job there!

Julian
