### ISSUE TITLE
training error!

### ISSUE THREAD

**Issue by zhangxujinsh** [schmidt-ju/crat-pred#2]
Information about the error is as follows
-------
  File "/home/bob/ws/code/crat-pred/model/crat_pred.py", line 167, in on_train_epoch_start
    self.trainer.accelerator_backend.setup_optimizers(self.trainer)
AttributeError: 'Trainer' object has no attribute 'accelerator_backend'

------

**Comment by schmidt-ju** [comment]
Hey,

thanks for the hint.
The reason for this might be a version mismatch of pytorch lightning.
Can you try if changing
`self.trainer.accelerator_backend.setup_optimizers(self.trainer)`
to
`self.trainer.accelerator.setup_optimizers(self.trainer)`
fixes your problem?

With the current training setup, the issue should only arise after 36 epochs.
Launch the training with the argument `--mod_freeze_epoch=0` to immediately see if this fixes the problem.

Best regards

Julian

**Comment by zhangxujinsh** [comment]
Julia:  
 
Thanks for your answer!  It works!
Could you upload the training log ?

Best regards

Bob

**Comment by Cram3r95** [comment]
Hi,

Regarding the version 1.9 of Pytorch-Lightning, that line of code should be as following:

```
self.trainer.strategy.setup_optimizers(self.trainer)
```

That is:

![image](https://user-images.githubusercontent.com/15740838/217815576-d3c97da6-05fa-45e9-ab71-da9777d48ab7.png)

**Comment by schmidt-ju** [comment]
Thanks for pointing it out!

I'm closing this issue, because the current conda environment.yml is compatible with the current version of the source code.

Still nice to know, that there was another api change!

Julian
