### ISSUE TITLE
LSTM ill-posed?

### ISSUE THREAD

**Issue by Cram3r95** [schmidt-ju/crat-pred#3]
Hi! This is an interesting repository with some SOTA concepts. Nevertheless, why do you use the output instead of the hidden state in the encoder?

According to the documentation:

output, (hn, cn) = rnn(input, (h0, c0))

We usually need hn (hidden state), whilst the output is usually used after the decoder, but you have this:

![imagen](https://user-images.githubusercontent.com/15740838/188415325-b2a90904-56ad-41ab-807b-bbe73c4bb1dc.png)

Any reason?

**Comment by schmidt-ju** [comment]
Hey,

I am not completely sure I understood your question correctly.
From my understanding it should not make a difference, whether you use the the last timestep of the output of the LSTM or the hidden state.
For multi-layer LSTMs, just make sure to use the hidden state of the last layer.

Keep in mind that I am using the nn.LSTM and not the nn.LSTMCell.
The whole "feeding back the hidden state" is already done inside nn.LSTM.


Julian

**Comment by Cram3r95** [comment]
Sorry for the late reply. I am already using the hidden state with num_layers = 1.

How are you able to obtain these metrics without map information? It is literally impossible to model these sequences:

![imagen](https://user-images.githubusercontent.com/15740838/190630273-355f3062-bc78-49ac-aff2-b44a812c9aaf.png)

If you do not provide map information

**Comment by schmidt-ju** [comment]
Hey,

are these predictions from our model?
Keep in mind that metrics given in the paper are averaged over the whole splits. So there might be scenarios, where the prediction is off (which inevitable in some map-reliant scenarios).

Julian

**Comment by Cram3r95** [comment]
No, these metrics and plots are from my code, but without map information, it is impossible to model curves, which are the main reason for metric drops. Do you obtain your metrics without map info?

**Comment by schmidt-ju** [comment]
Hey,

for sure there are some scenarios that are hard without map information.
I can once again confirm that all values in our paper are achieved without map information.


Julian
