### ISSUE TITLE
Data problems

### ISSUE THREAD

**Issue by 17805615161** [schmidt-ju/crat-pred#5]
I can't download the original data set, could you send me the Argoverse dataset?

**Comment by schmidt-ju** [comment]
Hey,

I will not send you the dataset but I just checked the Argoverse web page.
The download is still available:
https://www.argoverse.org/av1.html#download-link

You need:
- Argoverse HD Maps
- Argoverse Motion Forecasting v1.1

There should be no problems regarding the download from this page.


Julian
