### ISSUE TITLE
visualization

### ISSUE THREAD

**Issue by lunacou** [schmidt-ju/crat-pred#6]
Hi! How can I visualize the predictions?

**Comment by schmidt-ju** [comment]
Hey,

there is currently no visualization that I am able to publish.
Feel free to create your own visualization and contribute to this repository!

Thank you!


Julian

**Comment by Cram3r95** [comment]
Hi @lunacou,

You can use our qualitative results plot script:

https://github.com/Cram3r95/mapfe4mp/blob/master/evaluate/argoverse/generate_results_rel-rel.py

Since the model output is exactly the same than CRAT-PRED, that is, relative displacements.

**Comment by lunacou** [comment]
Thank you so much!

Best regards.

从 Windows 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>发送

发件人: Carlos Gómez ***@***.***>
发送时间: 2023年2月9日 20:38
收件人: ***@***.***>
抄送: ***@***.***>; ***@***.***>
主题: Re: [schmidt-ju/crat-pred] visualization (Issue #6)


Hi @lunacou<https://github.com/lunacou>,

You can use our qualitative results plot script:

https://github.com/Cram3r95/mapfe4mp/blob/master/evaluate/argoverse/generate_results_rel-rel.py

Since the model output is exactly the same than CRAT-PRED, that is, relative displacements.

―
