### ISSUE TITLE
Visualisation/Quantitative results.

### ISSUE THREAD

**Issue by djamelbenr** [schmidt-ju/crat-pred#9]
Dear authors,

I would like to thank you for making your remarkable work publicly accessible. 
I have two questions regarding the shared code and derived results (saved training weights, mainly); 

1-Is there a way to present them in a visually appealing format, such as visualizations or quantifiable results? 
I believe that being able to visualize the prediction outcomes in a multi-agent predictive system would greatly improve my understanding and provide a more intuitive understanding of the results.

2-I am also curious if it would be possible to train and test the CRAT-Pred algorithm using other BVE datasets, such as the HighD or NGSIM dataset.

Thank you for your time and consideration. I am eagerly awaiting your response :)

**Comment by Cram3r95** [comment]
Hi @djamelbenr,

You can use our qualitative results plot script:

https://github.com/Cram3r95/mapfe4mp/blob/master/evaluate/argoverse/generate_results_rel-rel.py

Since the model output is exactly the same than CRAT-PRED, that is, relative displacements.

**Comment by djamelbenr** [comment]
Oh! sounds good :) Thanks!!

**Comment by schmidt-ju** [comment]
Hey :D

thanks for helping each other out!
Is the plotting script working for you?

The code is a complete rework from the original paper version, so the original weights do not work anymore.
I once ran a training and achieved similar results with the code in this repository. However, I don't think I still have the weights. Isn't the training working for you? Should be easy to reproduce results similar to those in the paper.

1-Already solved. Thanks @Cram3r95!
2-For sure! You just have to adapt the dataloading.


Looking forward to hearing from you!


Julian

**Comment by schmidt-ju** [comment]
Closed due to inactivity.
